// ============================================================
// 植物静态配置 — 黑土区（10 种）
// ============================================================

import type { PlantConfig } from '../../types/plant';

const placeholderSprite = (name: string) => ({
  sheet: `plants/${name}/spritesheet.png`,
  frameWidth: 16,
  frameHeight: 16,
  stageFrameIndex: { seed: 0, sprout: 1, grow: 2, mature: 3 },
});

export const BLACK_SOIL_REGION_PLANTS: PlantConfig[] = [
  {
    id: 'ginseng',
    name: '人参',
    regionId: 'region_black',
    unlockCumulativeGold: 4500,
    purchasePrice: 120,
    sellPricePerUnit: 15,
    expectedBestYield: 12,
    growthMinutes: 86400,          // 60 天，跨季慢长
    plantableMonths: [3, 4, 5, 6, 7],
    wiltOutOfSeason: false,
    harvestType: 'perennial',
    reharvestMinutes: 10080,
    maxLifespanYears: 5,
    stageBoundaries: { seed: 0, sprout: 0.1, grow: 0.4, mature: 0.8 },
    soilMatch: { best: ['black_soil'], compatible: [] },
    season: { bestMonths: [4, 5, 6, 7, 8, 9], okMonths: [3, 10] },
    preferredWaterState: 'moist',
    sprite: placeholderSprite('ginseng'),
    difficultyFactor: 2.0,
  },
  {
    id: 'flax',
    name: '亚麻',
    regionId: 'region_black',
    unlockCumulativeGold: 3300,
    purchasePrice: 40,
    sellPricePerUnit: 13,
    expectedBestYield: 18,
    growthMinutes: 20160,          // 14 天
    stageBoundaries: { seed: 0, sprout: 0.12, grow: 0.45, mature: 0.85 },
    soilMatch: { best: ['black_soil'], compatible: ['brown_soil'] },
    plantableMonths: [3, 4, 5, 6, 7],
    season: { bestMonths: [4, 5, 6, 7], okMonths: [3, 8] },
    preferredWaterState: 'moist',
    sprite: placeholderSprite('flax'),
    difficultyFactor: 1.5,
  },
  {
    id: 'sugar_beet',
    name: '甜菜',
    regionId: 'region_black',
    unlockCumulativeGold: 3600,
    purchasePrice: 36,
    sellPricePerUnit: 12,
    expectedBestYield: 24,
    growthMinutes: 23040,          // 16 天
    stageBoundaries: { seed: 0, sprout: 0.1, grow: 0.4, mature: 0.8 },
    soilMatch: { best: ['black_soil'], compatible: ['brown_soil', 'tidal_soil'] },
    plantableMonths: [3, 4, 5, 6, 7],
    season: { bestMonths: [4, 5, 6, 7, 8, 9], okMonths: [3, 10] },
    preferredWaterState: 'moist',
    sprite: placeholderSprite('sugar_beet'),
    difficultyFactor: 1.5,
  },
  {
    id: 'buckwheat',
    name: '荞麦',
    regionId: 'region_black',
    unlockCumulativeGold: 3900,
    purchasePrice: 34,
    sellPricePerUnit: 11,
    expectedBestYield: 18,
    growthMinutes: 17280,          // 12 天
    stageBoundaries: { seed: 0, sprout: 0.12, grow: 0.45, mature: 0.85 },
    soilMatch: { best: ['black_soil'], compatible: ['brown_soil'] },
    plantableMonths: [6, 7, 8, 9, 10],
    season: { bestMonths: [5, 6, 7, 8], okMonths: [4, 9] },
    preferredWaterState: 'moist',
    sprite: placeholderSprite('buckwheat'),
    difficultyFactor: 1.5,
  },
  {
    id: 'highland_barley',
    name: '青稞',
    regionId: 'region_black',
    unlockCumulativeGold: 4200,
    purchasePrice: 38,
    sellPricePerUnit: 12,
    expectedBestYield: 18,
    growthMinutes: 20160,
    stageBoundaries: { seed: 0, sprout: 0.1, grow: 0.4, mature: 0.8 },
    soilMatch: { best: ['black_soil'], compatible: ['brown_soil'] },
    plantableMonths: [2, 3, 4, 5, 6],
    season: { bestMonths: [3, 4, 5, 6, 7], okMonths: [2, 8] },
    preferredWaterState: 'moist',
    sprite: placeholderSprite('highland_barley'),
    difficultyFactor: 1.6,
  },
  {
    id: 'sorghum',
    name: '高粱',
    regionId: 'region_black',
    unlockCumulativeGold: 4500,
    purchasePrice: 36,
    sellPricePerUnit: 12,
    expectedBestYield: 24,
    growthMinutes: 20160,
    stageBoundaries: { seed: 0, sprout: 0.1, grow: 0.4, mature: 0.8 },
    soilMatch: { best: ['black_soil'], compatible: ['brown_soil', 'dry_land'] },
    plantableMonths: [3, 4, 5, 6, 7],
    season: { bestMonths: [4, 5, 6, 7, 8, 9], okMonths: [3, 10] },
    preferredWaterState: 'moist',
    sprite: placeholderSprite('sorghum'),
    difficultyFactor: 1.5,
  },
  {
    id: 'velvet_bean',
    name: '黑豆',
    regionId: 'region_black',
    unlockCumulativeGold: 4800,
    purchasePrice: 42,
    sellPricePerUnit: 14,
    expectedBestYield: 18,
    growthMinutes: 23040,
    stageBoundaries: { seed: 0, sprout: 0.12, grow: 0.45, mature: 0.85 },
    soilMatch: { best: ['black_soil'], compatible: ['brown_soil'] },
    plantableMonths: [4, 5, 6, 7, 8],
    season: { bestMonths: [5, 6, 7, 8], okMonths: [4, 9] },
    preferredWaterState: 'moist',
    sprite: placeholderSprite('velvet_bean'),
    difficultyFactor: 1.6,
  },
  {
    id: 'mung_bean',
    name: '绿豆',
    regionId: 'region_black',
    unlockCumulativeGold: 5100,
    purchasePrice: 40,
    sellPricePerUnit: 13,
    expectedBestYield: 18,
    growthMinutes: 17280,
    stageBoundaries: { seed: 0, sprout: 0.15, grow: 0.5, mature: 0.85 },
    soilMatch: { best: ['black_soil'], compatible: ['tidal_soil', 'brown_soil'] },
    plantableMonths: [4, 5, 6, 7, 8],
    season: { bestMonths: [5, 6, 7, 8], okMonths: [4, 9] },
    preferredWaterState: 'moist',
    sprite: placeholderSprite('mung_bean'),
    difficultyFactor: 1.5,
  },
  {
    id: 'hemp',
    name: '大麻（工业）',
    regionId: 'region_black',
    unlockCumulativeGold: 5550,
    purchasePrice: 50,
    sellPricePerUnit: 23,
    expectedBestYield: 18,
    growthMinutes: 8640,           // 6 个月（工业大麻真实周期 4-5 月，游戏化为 6 月）
    stageBoundaries: { seed: 0, sprout: 0.1, grow: 0.4, mature: 0.8 },
    soilMatch: { best: ['black_soil'], compatible: [] },
    plantableMonths: [3, 4, 5, 6, 7],
    season: { bestMonths: [4, 5, 6, 7, 8], okMonths: [3, 9] },
    preferredWaterState: 'moist',
    sprite: placeholderSprite('hemp'),
    difficultyFactor: 1.8,
  },
  {
    id: 'wolfberry',
    name: '枸杞',
    regionId: 'region_black',
    unlockCumulativeGold: 6000,
    purchasePrice: 90,
    sellPricePerUnit: 12,
    expectedBestYield: 18,
    growthMinutes: 34560,         // 24 个月（枸杞定植到初产真实约 1.5-2 年）
    plantableMonths: [2, 3, 4, 5, 6],
    wiltOutOfSeason: false,
    harvestType: 'perennial',
    reharvestMinutes: 7200,
    maxLifespanYears: 6,
    stageBoundaries: { seed: 0, sprout: 0.1, grow: 0.4, mature: 0.8 },
    soilMatch: { best: ['black_soil'], compatible: ['brown_soil'] },
    season: { bestMonths: [4, 5, 6, 7, 8, 9], okMonths: [3, 10] },
    preferredWaterState: 'moist',
    sprite: placeholderSprite('wolfberry'),
    difficultyFactor: 1.8,
  },
];
