// ============================================================
// 植物静态配置 — 褐土/潮土组（10 种）
// ============================================================

import type { PlantConfig } from '../../types/plant';

const placeholderSprite = (name: string) => ({
  sheet: `plants/${name}/spritesheet.png`,
  frameWidth: 16,
  frameHeight: 16,
  stageFrameIndex: { seed: 0, sprout: 1, grow: 2, mature: 3 },
});

export const BROWN_TIDAL_REGION_PLANTS: PlantConfig[] = [
  {
    id: 'cotton',
    name: '棉花',
    regionId: 'region_brown_tidal',
    unlockCumulativeGold: 1800,
    purchasePrice: 22,
    sellPricePerUnit: 7,
    expectedBestYield: 18,
    growthMinutes: 20160,          // 14 天
    stageBoundaries: { seed: 0, sprout: 0.1, grow: 0.4, mature: 0.8 },
    soilMatch: { best: ['brown_soil', 'tidal_soil'], compatible: ['dry_land'] },
    plantableMonths: [3, 4, 5, 6, 7],
    season: { bestMonths: [4, 5, 6, 7, 8, 9], okMonths: [3, 10] },
    preferredWaterState: 'moist',
    sprite: placeholderSprite('cotton'),
    difficultyFactor: 1.2,
  },
  {
    id: 'sesame',
    name: '芝麻',
    regionId: 'region_brown_tidal',
    unlockCumulativeGold: 2070,
    purchasePrice: 24,
    sellPricePerUnit: 8,
    expectedBestYield: 18,
    growthMinutes: 17280,          // 12 天
    stageBoundaries: { seed: 0, sprout: 0.12, grow: 0.45, mature: 0.85 },
    soilMatch: { best: ['tidal_soil'], compatible: ['brown_soil', 'dry_land'] },
    plantableMonths: [4, 5, 6, 7, 8],
    season: { bestMonths: [5, 6, 7, 8], okMonths: [4, 9] },
    preferredWaterState: 'moist',
    sprite: placeholderSprite('sesame'),
    difficultyFactor: 1.2,
  },
  {
    id: 'sunflower',
    name: '向日葵',
    regionId: 'region_brown_tidal',
    unlockCumulativeGold: 1575,
    purchasePrice: 26,
    sellPricePerUnit: 8,
    expectedBestYield: 18,
    growthMinutes: 17280,
    stageBoundaries: { seed: 0, sprout: 0.1, grow: 0.4, mature: 0.8 },
    soilMatch: { best: ['brown_soil'], compatible: ['tidal_soil', 'dry_land'] },
    plantableMonths: [3, 4, 5, 6, 7],
    season: { bestMonths: [4, 5, 6, 7, 8], okMonths: [3, 9] },
    preferredWaterState: 'moist',
    sprite: placeholderSprite('sunflower'),
    difficultyFactor: 1.2,
  },
  {
    id: 'tobacco',
    name: '烟草',
    regionId: 'region_brown_tidal',
    unlockCumulativeGold: 1650,
    purchasePrice: 28,
    sellPricePerUnit: 9,
    expectedBestYield: 18,
    growthMinutes: 20160,
    stageBoundaries: { seed: 0, sprout: 0.1, grow: 0.4, mature: 0.8 },
    soilMatch: { best: ['brown_soil'], compatible: ['tidal_soil'] },
    plantableMonths: [2, 3, 4, 5, 6],
    season: { bestMonths: [4, 5, 6, 7], okMonths: [3, 8] },
    preferredWaterState: 'moist',
    sprite: placeholderSprite('tobacco'),
    difficultyFactor: 1.3,
  },
  {
    id: 'garlic',
    name: '大蒜',
    regionId: 'region_brown_tidal',
    unlockCumulativeGold: 1725,
    purchasePrice: 24,
    sellPricePerUnit: 8,
    expectedBestYield: 24,
    growthMinutes: 14400,          // 10 天
    stageBoundaries: { seed: 0, sprout: 0.15, grow: 0.5, mature: 0.85 },
    soilMatch: { best: ['tidal_soil'], compatible: ['brown_soil', 'dry_land'] },
    plantableMonths: [8, 9, 10, 11, 12],
    season: { bestMonths: [9, 10, 11, 3, 4, 5], okMonths: [8, 6] },
    preferredWaterState: 'moist',
    sprite: placeholderSprite('garlic'),
    difficultyFactor: 1.2,
  },
  {
    id: 'onion',
    name: '洋葱',
    regionId: 'region_brown_tidal',
    unlockCumulativeGold: 1800,
    purchasePrice: 25,
    sellPricePerUnit: 8,
    expectedBestYield: 24,
    growthMinutes: 14400,
    stageBoundaries: { seed: 0, sprout: 0.15, grow: 0.5, mature: 0.85 },
    soilMatch: { best: ['tidal_soil'], compatible: ['brown_soil'] },
    plantableMonths: [8, 9, 10, 11, 12],
    season: { bestMonths: [9, 10, 11, 3, 4], okMonths: [8, 5] },
    preferredWaterState: 'moist',
    sprite: placeholderSprite('onion'),
    difficultyFactor: 1.2,
  },
  {
    id: 'cabbage',
    name: '白菜',
    regionId: 'region_brown_tidal',
    unlockCumulativeGold: 1875,
    purchasePrice: 22,
    sellPricePerUnit: 7,
    expectedBestYield: 24,
    growthMinutes: 11520,          // 8 天
    stageBoundaries: { seed: 0, sprout: 0.15, grow: 0.5, mature: 0.85 },
    soilMatch: { best: ['tidal_soil', 'brown_soil'], compatible: ['dry_land'] },
    plantableMonths: [7, 8, 9, 10, 11],
    season: { bestMonths: [8, 9, 10, 11], okMonths: [7, 12] },
    preferredWaterState: 'moist',
    sprite: placeholderSprite('cabbage'),
    difficultyFactor: 1.15,
  },
  {
    id: 'radish',
    name: '萝卜',
    regionId: 'region_brown_tidal',
    unlockCumulativeGold: 1950,
    purchasePrice: 20,
    sellPricePerUnit: 6,
    expectedBestYield: 24,
    growthMinutes: 11520,
    stageBoundaries: { seed: 0, sprout: 0.15, grow: 0.5, mature: 0.85 },
    soilMatch: { best: ['tidal_soil'], compatible: ['brown_soil', 'dry_land'] },
    plantableMonths: [7, 8, 9, 10, 11],
    season: { bestMonths: [8, 9, 10, 11], okMonths: [7, 12] },
    preferredWaterState: 'moist',
    sprite: placeholderSprite('radish'),
    difficultyFactor: 1.15,
  },
  {
    id: 'rapeseed',
    name: '油菜',
    regionId: 'region_brown_tidal',
    unlockCumulativeGold: 2070,
    purchasePrice: 26,
    sellPricePerUnit: 8,
    expectedBestYield: 18,
    growthMinutes: 17280,
    stageBoundaries: { seed: 0, sprout: 0.1, grow: 0.4, mature: 0.8 },
    soilMatch: { best: ['tidal_soil', 'brown_soil'], compatible: ['paddy_field'] },
    plantableMonths: [8, 9, 10, 11, 12],
    season: { bestMonths: [9, 10, 11, 3, 4, 5], okMonths: [8, 6] },
    preferredWaterState: 'moist',
    sprite: placeholderSprite('rapeseed'),
    difficultyFactor: 1.2,
  },
  {
    id: 'pepper',
    name: '辣椒',
    regionId: 'region_brown_tidal',
    unlockCumulativeGold: 2220,
    purchasePrice: 30,
    sellPricePerUnit: 10,
    expectedBestYield: 24,
    growthMinutes: 20160,
    stageBoundaries: { seed: 0, sprout: 0.1, grow: 0.4, mature: 0.8 },
    soilMatch: { best: ['brown_soil'], compatible: ['tidal_soil', 'dry_land'] },
    plantableMonths: [2, 3, 4, 5, 6],
    season: { bestMonths: [4, 5, 6, 7, 8, 9], okMonths: [3, 10] },
    preferredWaterState: 'moist',
    sprite: placeholderSprite('pepper'),
    difficultyFactor: 1.3,
  },
];
