// ============================================================
// 植物静态配置 — 水稻土区（10 种）
// 水田：水稻、莲藕、茭白、荸荠
// 旱地：大豆、空心菜、水芹、油菜、蚕豆、小麦
// ============================================================

import type { PlantConfig } from "../../types/plant";

const placeholderSprite = (name: string) => ({
    sheet: `plants/${name}/spritesheet.png`,
    frameWidth: 16,
    frameHeight: 16,
    stageFrameIndex: { seed: 0, sprout: 1, grow: 2, mature: 3 },
});

export const PADDY_REGION_PLANTS: PlantConfig[] = [
    // ── 水田作物 ─────────────────────────────────────────────────
    {
        id: "rice",
        name: "水稻",
        regionId: "region_paddy",
        unlockCost: 450,
        purchasePrice: 175,
        sellPricePerUnit: 500,
        harvestYield: 1,
        growthMinutes: 360, // 6h
        stageBoundaries: { seed: 0, sprout: 0.15, grow: 0.45, mature: 0.85 },
        allowedLandTypeId: "paddy_field",
        preferredWaterState: "flooded",
        sprite: placeholderSprite("rice"),
        difficultyFactor: 1.0,
    },
    {
        id: "lotus_root",
        name: "莲藕",
        regionId: "region_paddy",
        unlockCost: 450,
        purchasePrice: 140,
        sellPricePerUnit: 338,
        harvestYield: 1,
        growthMinutes: 270, // 4.5h
        stageBoundaries: { seed: 0, sprout: 0.15, grow: 0.45, mature: 0.85 },
        allowedLandTypeId: "paddy_field",
        preferredWaterState: "flooded",
        sprite: placeholderSprite("lotus_root"),
        difficultyFactor: 1.0,
    },
    {
        id: "water_bamboo",
        name: "茭白",
        regionId: "region_paddy",
        unlockCost: 750,
        purchasePrice: 100,
        sellPricePerUnit: 118,
        harvestYield: 1,
        growthMinutes: 180, // 3h
        harvestType: "perennial",
        reharvestMinutes: 60, // 1h
        maxHarvests: 3,
        stageBoundaries: { seed: 0, sprout: 0.2, grow: 0.5, mature: 0.85 },
        allowedLandTypeId: "paddy_field",
        preferredWaterState: "flooded",
        sprite: placeholderSprite("water_bamboo"),
        difficultyFactor: 1.0,
    },
    {
        id: "water_chestnut",
        name: "荸荠",
        regionId: "region_paddy",
        unlockCost: 270,
        purchasePrice: 80,
        sellPricePerUnit: 112,
        harvestYield: 2,
        growthMinutes: 240, // 4h
        stageBoundaries: { seed: 0, sprout: 0.15, grow: 0.45, mature: 0.85 },
        allowedLandTypeId: "paddy_field",
        preferredWaterState: "flooded",
        sprite: placeholderSprite("water_chestnut"),
        difficultyFactor: 1.0,
    },

    // ── 旱地作物 ─────────────────────────────────────────────────
    {
        id: "soybean",
        name: "大豆",
        regionId: "region_paddy",
        unlockCost: 0, // 初始解锁
        purchasePrice: 20,
        sellPricePerUnit: 16,
        harvestYield: 1,
        growthMinutes: 30,
        harvestType: "perennial",
        reharvestMinutes: 10,
        maxHarvests: 3,
        stageBoundaries: { seed: 0, sprout: 0.2, grow: 0.5, mature: 0.85 },
        allowedLandTypeId: "dry_land",
        preferredWaterState: "moist",
        sprite: placeholderSprite("soybean"),
        difficultyFactor: 1.0,
    },
    {
        id: "water_spinach",
        name: "空心菜",
        regionId: "region_paddy",
        unlockCost: 0, // 初始解锁
        purchasePrice: 10,
        sellPricePerUnit: 10,
        harvestYield: 1,
        growthMinutes: 25,
        harvestType: "perennial",
        reharvestMinutes: 12,
        maxHarvests: 5,
        stageBoundaries: { seed: 0, sprout: 0.2, grow: 0.5, mature: 0.85 },
        allowedLandTypeId: "dry_land",
        preferredWaterState: "moist",
        sprite: placeholderSprite("water_spinach"),
        difficultyFactor: 1.0,
    },
    {
        id: "water_celery",
        name: "水芹",
        regionId: "region_paddy",
        unlockCost: 75,
        purchasePrice: 15,
        sellPricePerUnit: 12,
        harvestYield: 1,
        growthMinutes: 35,
        harvestType: "perennial",
        reharvestMinutes: 10,
        maxHarvests: 5,
        stageBoundaries: { seed: 0, sprout: 0.2, grow: 0.5, mature: 0.85 },
        allowedLandTypeId: "dry_land",
        preferredWaterState: "moist",
        sprite: placeholderSprite("water_celery"),
        difficultyFactor: 1.0,
    },
    {
        id: "rapeseed",
        name: "油菜",
        regionId: "region_paddy",
        unlockCost: 900,
        purchasePrice: 40,
        sellPricePerUnit: 105,
        harvestYield: 1,
        growthMinutes: 90, // 1.5h
        stageBoundaries: { seed: 0, sprout: 0.15, grow: 0.45, mature: 0.85 },
        allowedLandTypeId: "dry_land",
        preferredWaterState: "moist",
        sprite: placeholderSprite("rapeseed"),
        difficultyFactor: 1.0,
    },
    {
        id: "broad_bean",
        name: "蚕豆",
        regionId: "region_paddy",
        unlockCost: 1500,
        purchasePrice: 50,
        sellPricePerUnit: 63,
        harvestYield: 2,
        growthMinutes: 90, // 1.5h
        stageBoundaries: { seed: 0, sprout: 0.15, grow: 0.45, mature: 0.85 },
        allowedLandTypeId: "dry_land",
        preferredWaterState: "moist",
        sprite: placeholderSprite("broad_bean"),
        difficultyFactor: 1.0,
    },
    {
        id: "wheat",
        name: "小麦",
        regionId: "region_paddy",
        unlockCost: 2250,
        purchasePrice: 60,
        sellPricePerUnit: 81,
        harvestYield: 2,
        growthMinutes: 120, // 2h
        stageBoundaries: { seed: 0, sprout: 0.12, grow: 0.42, mature: 0.82 },
        allowedLandTypeId: "dry_land",
        preferredWaterState: "moist",
        sprite: placeholderSprite("wheat"),
        difficultyFactor: 1.0,
    },
    {
        id: "gorgon",
        name: "苏芡",
        regionId: "region_paddy",
        unlockCost: 99999999,
        isRare: true,
        purchasePrice: 0,
        sellPricePerUnit: 930,
        harvestYield: 1,
        growthMinutes: 420, // 7h
        stageBoundaries: { seed: 0, sprout: 0.15, grow: 0.45, mature: 0.85 },
        allowedLandTypeId: "paddy_field",
        preferredWaterState: "flooded",
        sprite: placeholderSprite("gorgon"),
        difficultyFactor: 1.0,
    },
    {
        id: "saffron",
        name: "藏红花",
        regionId: "region_paddy",
        unlockCost: 99999999,
        isRare: true,
        purchasePrice: 0,
        sellPricePerUnit: 400,
        harvestYield: 1,
        growthMinutes: 180, // 3h
        stageBoundaries: { seed: 0, sprout: 0.15, grow: 0.45, mature: 0.85 },
        allowedLandTypeId: "dry_land",
        preferredWaterState: "moist",
        sprite: placeholderSprite("saffron"),
        difficultyFactor: 1.0,
    },
]
