// ============================================================
// 成就静态配置（23 个，从易到难）
// ============================================================

import type { AchievementDefinition } from '../types/achievement';

export const ACHIEVEMENT_CONFIGS: AchievementDefinition[] = [
  // ── EASY（7 个）──────────────────────────────────────────────
  {
    id: 'ach_first_harvest',
    name: '首次收获',
    description: '收获任意作物 1 次',
    difficulty: 'easy',
    tracker: 'totalHarvest',
    target: 1,
    reward: { type: 'gold', value: 50 },
  },
  {
    id: 'ach_first_sell',
    name: '第一桶金',
    description: '累计出售 10 次',
    difficulty: 'easy',
    tracker: 'totalSell',
    target: 10,
    reward: { type: 'gold', value: 100 },
  },
  {
    id: 'ach_ten_plots',
    name: '初具规模',
    description: '扩建地块到 10 块',
    difficulty: 'easy',
    tracker: 'totalPlots',
    target: 10,
    reward: { type: 'seeds', value: 10, plantId: 'soybean' },
  },
  {
    id: 'ach_first_fertilizer',
    name: '施肥新手',
    description: '使用肥料 1 次',
    difficulty: 'easy',
    tracker: 'totalFertilizer',
    target: 1,
    reward: { type: 'gold', value: 50 },
  },
  {
    id: 'ach_five_crops',
    name: '小试牛刀',
    description: '收获 5 种不同作物',
    difficulty: 'easy',
    tracker: 'uniqueCropsHarvested',
    target: 5,
    reward: { type: 'seeds', value: 5, plantId: 'water_spinach' },
  },
  {
    id: 'ach_first_task',
    name: '任务新人',
    description: '完成 1 个任务',
    difficulty: 'easy',
    tracker: 'tasksCompleted',
    target: 1,
    reward: { type: 'gold', value: 150 },
  },
  {
    id: 'ach_first_region',
    name: '开拓荒地',
    description: '解锁褐土/潮土区',
    difficulty: 'easy',
    tracker: 'regionsUnlocked',
    target: 2,
    reward: { type: 'gold', value: 200 },
  },

  // ── MEDIUM（8 个）────────────────────────────────────────────
  {
    id: 'ach_fifty_harvests',
    name: '丰收在望',
    description: '累计收获 50 次',
    difficulty: 'medium',
    tracker: 'totalHarvest',
    target: 50,
    reward: { type: 'harvest', value: 5, plantId: 'lotus_root' },
  },
  {
    id: 'ach_hundred_tasks',
    name: '任务达人',
    description: '完成 10 个任务',
    difficulty: 'medium',
    tracker: 'tasksCompleted',
    target: 10,
    reward: { type: 'gold', value: 300 },
  },
  {
    id: 'ach_all_paddy',
    name: '水稻土大师',
    description: '图鉴收集水稻土区全部 10 种',
    difficulty: 'medium',
    tracker: 'uniqueCropsHarvested',
    target: 10,
    reward: { type: 'seeds', value: 5, plantId: 'rice' },
  },
  {
    id: 'ach_rich',
    name: '小富翁',
    description: '累计赚取 5000 金币',
    difficulty: 'medium',
    tracker: 'totalEarned',
    target: 5000,
    reward: { type: 'buff', value: 2, buffType: 'sellPrice', description: '作物售价 +2%（永久）' },
  },
  {
    id: 'ach_twenty_plots',
    name: '农场主',
    description: '扩建地块到 20 块',
    difficulty: 'medium',
    tracker: 'totalPlots',
    target: 20,
    reward: { type: 'gold', value: 300 },
  },
  {
    id: 'ach_perennial',
    name: '多年生专家',
    description: '收获多年生作物 20 次',
    difficulty: 'medium',
    tracker: 'perennialHarvest',
    target: 20,
    reward: { type: 'seeds', value: 3, plantId: 'water_bamboo' },
  },
  {
    id: 'ach_black_unlock',
    name: '黑土探索者',
    description: '解锁黑土区',
    difficulty: 'medium',
    tracker: 'regionsUnlocked',
    target: 3,
    reward: { type: 'gold', value: 500 },
  },
  {
    id: 'ach_ten_harvests',
    name: '小有收获',
    description: '累计收获 10 次',
    difficulty: 'easy',
    tracker: 'totalHarvest',
    target: 10,
    reward: { type: 'seeds', value: 3, plantId: 'water_celery' },
  },

  // ── HARD（6 个）──────────────────────────────────────────────
  {
    id: 'ach_two_hundred',
    name: '资深农夫',
    description: '累计收获 200 次',
    difficulty: 'hard',
    tracker: 'totalHarvest',
    target: 200,
    reward: { type: 'gold', value: 500 },
  },
  {
    id: 'ach_master_farmer',
    name: '种植大师',
    description: '图鉴收集全部 30 种作物',
    difficulty: 'hard',
    tracker: 'uniqueCropsHarvested',
    target: 30,
    reward: { type: 'buff', value: 3, buffType: 'sellPrice', description: '作物售价 +3%（永久）' },
  },
  {
    id: 'ach_millionaire',
    name: '大富翁',
    description: '累计赚取 50000 金币',
    difficulty: 'hard',
    tracker: 'totalEarned',
    target: 50000,
    reward: { type: 'buff', value: 5, buffType: 'fertilizerPower', description: '肥料效果 +5%（永久）' },
  },
  {
    id: 'ach_task_master',
    name: '任务专家',
    description: '完成所有 40 个任务',
    difficulty: 'hard',
    tracker: 'tasksCompleted',
    target: 40,
    reward: { type: 'gold', value: 1000 },
  },
  {
    id: 'ach_max_plots',
    name: '庄园领主',
    description: '所有区域地块都到上限 (54 块)',
    difficulty: 'hard',
    tracker: 'totalPlots',
    target: 54,
    reward: { type: 'buff', value: 2, buffType: 'extraYield', description: '额外收获概率 +2%（永久）' },
  },
  {
    id: 'ach_hell_clear',
    name: '地狱挑战者',
    description: '完成 5 个地狱难度任务',
    difficulty: 'hard',
    tracker: 'hellTasksCompleted',
    target: 5,
    reward: { type: 'gold', value: 800 },
  },

  // ── LEGENDARY（2 个）─────────────────────────────────────────
  {
    id: 'ach_legend_harvest',
    name: '传说级农夫',
    description: '累计收获 1000 次',
    difficulty: 'legendary',
    tracker: 'totalHarvest',
    target: 1000,
    reward: { type: 'buff', value: 5, buffType: 'growthSpeed', description: '生长速度 +5%（永久）' },
  },
  {
    id: 'ach_complete_game',
    name: '完美农场',
    description: '完成所有成就',
    difficulty: 'legendary',
    tracker: 'tasksCompleted',
    target: 0, // 特殊处理：在 _checkAchievements 里判断
    reward: { type: 'buff', value: 5, buffType: 'sellPrice', description: '作物售价 +5%（永久）' },
  },
];

export const getAchievementById = (id: string) =>
  ACHIEVEMENT_CONFIGS.find((a) => a.id === id) ?? null;
